language:
  - go 
sudo: required
services: docker
go:
  - "1.12"

script:
  - mkdir -p /home/travis/gopath/src/github.com/kubernetes-helm/chartmuseum/
  - cp -ar *  /home/travis/gopath/src/github.com/kubernetes-helm/chartmuseum/
  - make
  - make build
  - docker build . -t liupeng0518/chartmuseum:v0.7.1

after_success:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push liupeng0518/chartmuseum:v0.7.1
